# Generated by Django 4.1.7 on 2023-04-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
